language: php
php:
  - "5.4"
  - "5.3"
before_script:
 - mysql -e 'create database moodle default character set UTF8 collate UTF8_bin;'
 - pear channel-discover pear.phpunit.de
 - pear channel-discover pear.symfony.com
 - pear install pear.phpunit.de/DbUnit
 - mv config-test.php config.php
 - mkdir -m777 /home/travis/moodledata
 - php admin/tool/phpunit/cli/init.php
