language: php
php:
  - "5.5"
env:
 - DB=mysqli TEST=unit
 - DB=pgsql  TEST=behat
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
before_script:
 - sudo apt-get update > /dev/null
 - composer self-update
 - composer install --dev --prefer-dist
 - pear channel-discover pear.phpunit.de
 - pear channel-discover pear.symfony.com
 - pear install pear.phpunit.de/DbUnit
 - phpenv rehash
 - cp config-dist.php config.php
 - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%/home/example%$HOME% -e 's%\(\$CFG.*phpu\)%\n\1%' config.php"
 - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%/home/example%$HOME% -e 's%\(\$CFG.*bht\)%\n\1%' config.php"
 - if [ '$DB' = 'mysqli' ]; then sh -c "mysql -e 'create database moodle default character set UTF8 collate UTF8_bin;'; sed -i -e s/\'pgsql\'/\'mysqli\'/ -e s/\'username\'/\'root\'/ config.php"; fi
 - if [ '$DB' = 'pgsql' ]; then sh -c "psql -c 'create database moodle;' -U postgres; sed -i s/\'username\'/\'postgres\'/ config.php"; fi
 - mkdir -m777 $HOME/moodledata
 - php admin/tool/phpunit/cli/init.php
 - if [ '$TEST = 'behat' ]; then sh -c " (php -S localhost:8000 &) 2> /dev/null > /dev/null; wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar; (java -jar selenium-server-standalone-2.31.0.jar &) 2> /dev/null > /dev/null; php admin/tool/behat/cli/init.php"; fi

script:
 - if [ '$TEST = 'behat' ]; vendor/bin/behat --config /home/travis/bht_moodledata/behat/behat.yml; fi
 - if [ '$TEST = 'unit' ]; phpunit

notifications:
  email:
    - david.scotson@gla.ac.uk
    - howard.miller@gla.ac.uk
