language: php
php:
  - "5.4"
  - "5.3"
env:
 - DB=sqlite
before_script:
 - pear channel-discover pear.phpunit.de
 - pear channel-discover pear.symfony.com
 - pear install pear.phpunit.de/DbUnit
 - phpenv rehash
 - cp config-dist.php config.php
 - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%/home/example%$HOME% -e 's%\(\$CFG.*phpu\)%\n\1%' config.php"
 - mkdir -m777 $HOME/moodledata
 - php admin/tool/phpunit/cli/init.php
