language: php
php:
  - "5.4"
  - "5.3"
env:
 - DB=mysqli
 - DB=pgsql
before_script:
 - pear channel-discover pear.phpunit.de
 - pear channel-discover pear.symfony.com
 - pear install pear.phpunit.de/DbUnit
 - phpenv rehash
 - cp config-dist.php config.php
 - sh -c "sed -i -e s/'username'/'root'/ -e s/'password'/''/ -e s/example.com/localhost/ -e s-/home/example-$HOME- -e s_//.*\$CFG-\>phpu_\$CFG-\>phpu_ config.php"
 - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -e 'create database moodle default character set UTF8 collate UTF8_bin;'; fi"
 - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database moodle;' -U postgres; fi"
 - sh -c "if [ '$DB' = 'pgsql' ]; then sed -i s/\'mysqli\'/\'pgsql\'/ -e s/\'root\'/\'postgres\'/ config.php; fi"
 - mkdir -m777 $HOME/moodledata
 - php admin/tool/phpunit/cli/init.php
