language: php
php:
  - "5.4"
  - "5.3"
env:
 - DB=mysqli
 - DB=pgsql
before_script:
 - pear channel-discover pear.phpunit.de
 - pear channel-discover pear.symfony.com
 - pear install pear.phpunit.de/DbUnit
 - phpenv rehash
 - cp config-dist.php config.php
 - sed -i s/\'username\'/\'root\'/ config.php
 - sed -i s/\'password\'/\'\'/ config.php
 - sed -i s/example.com/localhost/ config.php
 - sed -i s:/home/example:$HOME: config.php
 - sed -i s://.*\$CFG-\>phpu:\$CFG-\>phpu: config.php
 - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -e 'create database moodle default character set UTF8 collate UTF8_bin;'; fi"
 - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database moodle;' -U postgres; fi"
 - sh -c "if [ '$DB' = 'pgsql' ]; then sed -i s/\'mysqli\'/\'pgsql\'/ config.php; fi"
 - sh -c "if [ '$DB' = 'pgsql' ]; then sed -i s/\'root\'/\'postgres\'/ config.php; fi"
 - mkdir -m777 $HOME/moodledata
 - php admin/tool/phpunit/cli/init.php
