language: php
php:
  - "5.4"
  - "5.3"
env:
 - DB=mysql
 - DB=postgres
before_script:
 - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database moodle default character set UTF8 collate UTF8_bin;'; fi"
 - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database moodle;' -U postgres; fi"
 - pear channel-discover pear.phpunit.de
 - pear channel-discover pear.symfony.com
 - pear install pear.phpunit.de/DbUnit
 - phpenv rehash
 - mv config-travis.php config.php
 - mkdir -m777 $HOME/moodledata
 - php admin/tool/phpunit/cli/init.php
