language: php
php:
  - "5.4"
  - "5.3"
before_script:
 - mysql -e 'create database travis default character set UTF8 collate UTF8_bin;'
 - pear install phpunit/DbUnit
 - mv config-test.php config.php
 - mkdir -m777 /var/phpu_moodledata
 - mkdir -m777 /var/travis_moodledata
 - php admin/tool/phpunit/cli/init.php
