<?php

// This file is part of the Echo360 Moodle Plugin - http://moodle.org/
//
// The Echo360 Moodle Plugin is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The Echo360 Moodle Plugin is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with the Echo360 Moodle Plugin.  If not, see <http://www.gnu.org/licenses/>.
 
/**
 * This file contains the language strings for the Echo360 Configuration Block
 *
 * @package    block                                                    
 * @subpackage echo360_configuration
 * @copyright  2011 Echo360 Inc
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later 
 */

    $string['configuration'] = "Echo360 Configuration";
    $string['echosystem_connection_details'] = "Echo360 EchoSystem Connection Details";
    $string['echosystem_connection_details_description'] = "Enter the connection details for the EchoSystem Server that this Moodle installation will communicate with. The Trusted System Consumer Key and Trusted System Consumer Secret can be obtained from the EchoSystem Web Administration Interface at &quot;Configuration &#8594; Trusted Systems&quot;.";
    $string['echosystem_url'] = "EchoSystem URL";
    $string['default_echosystem_url'] = "http://echosystem.your.institution.edu:8080/";
    $string['echosystem_url_description'] = "The full URL to your EchoSystem installation including the protocol (http or https) and port number.";
    $string['trusted_system_consumer_key'] = "Trusted System Consumer Key";
    $string['default_trusted_system_consumer_key'] = "";
    $string['trusted_system_consumer_key_description'] = "The key entered for this external system into EchoSystem.";
    $string['trusted_system_consumer_secret'] = "Trusted System Consumer Secret";
    $string['default_trusted_system_consumer_secret'] = "";
    $string['trusted_system_consumer_secret_description'] = "The key generated by EchoSystem for this external system. The key will consist of a long series of randomised letters, numbers and symbols.";
    $string['moodle_course_mapping_details'] = "Moodle Course Mapping Details";
    $string['moodle_course_mapping_details_description'] = "Select the Moodle Course Field that will be entered in EchoSystem as the Section External ID";
    $string['moodle_external_id_field'] = "Moodle Course Field";
    $string['default_moodle_external_id_field'] = "shortname";
    $string['moodle_external_id_field_description'] = "This is the field in Moodle that will be passed to EchoSystem to associate a Moodle course with an EchoSystem section.";
    $string['moodle_permission_mapping_details'] = "Moodle Role Mapping Details";
    $string['moodle_permission_mapping_details_description'] = "Enter the Moodle permission required to map a user into each of the following EchoSystem roles.";
    $string['moodle_instructor_perm'] = "Instructor";
    $string['default_moodle_instructor_perm'] = "moodle/course:manageactivities";
    $string['moodle_instructor_perm_description'] = "This is the minimum capability required in Moodle to be recognised as an instructor in EchoSystem.";
    $string['moodle_student_perm'] = "Student";
    $string['default_moodle_student_perm'] = "moodle/grade:view";
    $string['moodle_student_perm_description'] = "This is the minimum capability required in Moodle to be recognised as a student in EchoSystem. If a user does not have at least this capability in the course that this block is placed in, they will not be allowed to access the EchoSystem.";
    $string['security_realm'] = "Security Realm";
    $string['security_realm_help'] = "This is the security-realm which is used for non-instructor users to further qualify the user name.  Two non-instructor users with the same user name and different realms will be considered different users by the EchoSystem.  If you are only using one method of authentication to the EchoSystem, then realm can have any arbitrary value. If you are using  multiple authentication providers (such as a seamless tool, and LDAP), but the same user name represents the same individual across authentication providers, then you should use the same realm for all authentication providers. If this is not true, then providers in which a user name represents the same user should use the same realm.";
    $string['default_security_realm'] = "default";
    $string['security_realm_description'] = "The security realm used by EchoSystem to identify unique users from separate systems.";

    // This is the global plugin name
    $string['pluginname'] = $string['blockname'] = "Echo360 Configuration";

    // These are the language strings for the capabilities
    $string['echo360_configuration:viewasinstructor'] = "View EchoCenter as EchoSystem Instructor";
    $string['echo360_configuration:viewasstudent'] = "View EchoCenter as Student";
    $string['databaseid'] = "Course database ID";
?>
